social_problems_rails_bg/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homes#index'

  resources :homes
  resources :problems
  
  scope 'api' do
    post 'login' => 'android_api#login'
    post 'register' => 'android_api#register'
    post 'send_signal' => 'android_api#send_signal'
  end

  get 'edit_info' => 'person_infos#change_info', as: :edit_info
  patch 'create' => 'person_infos#create'
  post 'create' => 'person_infos#create'

end

social_problems_rails_bg/app/models/api_token.rb
class ApiToken < ActiveRecord::Base
	belongs_to :user
end

social_problems_rails_bg/app/models/person_info.rb
class PersonInfo < ActiveRecord::Base
	belongs_to :user
end

social_problems_rails_bg/app/models/problem.rb
class Problem < ActiveRecord::Base
	belongs_to :user	
	validates :description, presence: true
end

social_problems_rails_bg/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tokens
  has_many :problems
  has_one :person_info
end

social_problems_rails_bg/app/controllers/android_api_controller.rb
require 'digest/sha1'

class AndroidApiController < ApplicationController
	before_action :check_token, except: [:login, :register]

	skip_before_action :verify_authenticity_token
	skip_before_action :authenticate_user!

	def login
		token = get_user_token
		render plain: token
	end

	def get_user_token
		user = User.find_by email: params[:email]
		if user && user.valid_password?(params[:password])
			set_session user
		else
			set_error_messages "Error"
		end
	end

	def set_session user
		token = generate_token
		session = ApiToken.new token: token, user: user
		session.save ? token : "Error"
	end

	def generate_token
		Digest::SHA1.hexdigest params[:email] + ApiToken.count.to_s
	end

	def register
		@user = User.new user_params

		if @user.save && params[:confirm_password] == params[:password]
			render plain: "Success"
		else	
			set_user_errors "Can't register"
		end
	end

	def user_params
		params.permit(:email, :password)	
	end

	def set_user_errors custom_error
		render plain: custom_error || @user.errors.full_messages.join("\n")
	end

	def send_signal
		@problem = Problem.new send_signal_params
		@problem.user = current_user
		@problem.save
	end

	def current_user
		current_user ||= set_user
	end

	def set_user
		token = ApiToken.find_by(token: token_params)
		token.user
	end

	def check_token
        render(plain: "Error") if ApiToken.find_by(token: token_params).nil?
	end

    def token_params
        params.require(:token)
    end

	def send_signal_params
        params.permit(:description, :lat_two, :lat_one)
	end
end

social_problems_rails_bg/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

social_problems_rails_bg/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end
	
end

social_problems_rails_bg/app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		@problems = Problem.where "user_id = ?", current_user
	end
end

social_problems_rails_bg/app/controllers/person_infos_controller.rb
class PersonInfosController < ApplicationController
	def change_info
		if not current_user.person_info
			@infos = PersonInfo.new user_id: current_user
		else
			@infos = current_user.person_info
		end
	end

	def create
		if current_user.person_info
			current_user.person_info.update update_params
		else
			current_user.person_info = PersonInfo.new update_params
			current_user.save
		end

		redirect_to :back
	end

	def update_params
		params.require(:person_info).permit!
	end
end

social_problems_rails_bg/app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	def new 
		@problem = Problem.new
	end

	def create
		@problem = Problem.new problem_params
		upload_file if params[:problem][:file]
		@problem.user = current_user
		if @problem.save
			flash[:notice] = "Сигнализирането за нередност е създадено успешно"
			redirect_to :back
		else
			flash[:alert] = @problem.errors.full_messages.join("<br />")
			render 'new'
		end
	end

	def upload_file
	    name = params[:problem][:file].original_filename
	    directory = "public/images/upload"
	    path = File.join(directory, name)
	    File.open(path, "wb") { |f| f.write(params[:problem][:file].read) }
	    @problem.picture = path
	end

	def show
		@problem = Problem.find params[:id]
	end

	def index
		render 'new'
	end

	private

	def problem_params
		params.require(:problem).permit(:lat_one, :lat_two, :description)
	end
end

social_problems_rails_bg/app/helpers/android_api_helper.rb
module AndroidApiHelper
end

social_problems_rails_bg/app/helpers/application_helper.rb
module ApplicationHelper
end

social_problems_rails_bg/app/helpers/home_helper.rb
module HomeHelper
end

social_problems_rails_bg/app/helpers/homes_helper.rb
module HomesHelper
end

social_problems_rails_bg/app/helpers/person_infos_helper.rb
module PersonInfosHelper
end

social_problems_rails_bg/app/helpers/problems_helper.rb
module ProblemsHelper
end

social_problems_rails_bg/app/helpers/users_helper.rb
module UsersHelper

  def devise_error_messages_c!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-warning">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

social_problems_rails_bg/app/views/homes/index.html.erb
<% @problems.each do |problem| %>
	<div class="col-lg-3 col-md-6" style="width:100%;">
	  <div class="panel panel-red">
	    <div class="panel-heading">
	      <div class="row">
	        <div class="col-xs-9 text-left">
	          <div><%= problem.id %></div>
	        </div>
	      </div>
	    </div>
	    <div class="panel-footer" style="color: black;">
	      <span class="pull-left"><%= problem.description %></span>
	      <span class="pull-right"><%= button_to 'Read More', problem_path(problem.id), method: :get, class: "btn btn-primary btn-lg round", type: "button"%></span>	
	      <div class="clearfix"></div>
	    </div>
	  </div>
	</div>
<% end %>

social_problems_rails_bg/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialProblems</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "SocialProblems", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Начало", root_path %></li>
          <li><%= link_to "Информация", edit_info_path %></li>
          <li><%= link_to "Сигнализиране за нередност", new_problem_path %></li>
          <!--Logged in as <strong><%= current_user.email %></strong>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Редактиране на профила', edit_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Излизане", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Регистрирай се", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Влизане", new_user_session_path, :class => 'navbar-link'  %></li>
        </ul>
      <% end %>
      <!--<li class="active"><a href="#">Link</a></li> -->
    </ul> 
  </div><!-- /.navbar-collapse -->
</nav>
<% if notice %>
  <p class="alert alert-success" style="width:96%; margin: 0px auto;"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger" style="width:96%; margin: 0px auto;"><%= alert %></p>
<% end %>
<div class="banner_wrapper">
  <div class="banner_image">
  </div>
</div>
<div class="container">
  <%= yield %>
</div>
<div class="footerholder">
  <div class="footer">
      <p> © 2015 Social Problems. Всички права запазени.</p>
  </div>
</div>
</body>
</html>

social_problems_rails_bg/app/views/person_infos/change_info.html.erb
<div class="form-horizontal">
<div class="alert alert-danger" role="alert"><h2>Информация за мен</h2></div>
<%= form_for(@infos, url: { action: 'create' } , class: "form-horizontal") do |f| %>
	<div class="form-group">
      <label class="col-sm-2 control-label">Населено място</label>
      <div class="col-sm-10">
        <%= f.text_field :town, autocomplete: "off", class: "form-control", placeholder: "Населено място" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Име</label>
      <div class="col-sm-10">
        <%= f.text_field :first_name, autocomplete: "off", class: "form-control", placeholder: "Име" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Презиме</label>
      <div class="col-sm-10">
        <%= f.text_field :second_name, autocomplete: "off", class: "form-control", placeholder: "Презиме" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Фамилия</label>
      <div class="col-sm-10">
        <%= f.text_field :last_name, autocomplete: "off", class: "form-control", placeholder: "Фамилия" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Адрес</label>
      <div class="col-sm-10">
        <%= f.text_field :address, autocomplete: "off", class: "form-control", placeholder: "Адрес" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Телефон</label>
      <div class="col-sm-10">
        <%= f.text_field :mobile_num, autocomplete: "off", class: "form-control", placeholder: "Телефон" %>
      </div>
    </div>
     <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Запазване", class: "btn btn-default" %> 
      </div>
    </div>
<% end %>
</div>

social_problems_rails_bg/app/views/problems/new.html.erb
<div class="form-horizontal">
<div class="alert alert-danger" role="alert"><h2>Сигнализиране за нередност</h2></div>
<%= form_for(@problem, url: { action: 'create' } , class: "form-horizontal") do |f| %>
	<div class="form-group">
      <label class="col-sm-2 control-label">Описание</label>
      <div class="col-sm-10">
        <%= f.text_area :description, autocomplete: "off", class: "form-control", placeholder: "Описание" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Снимка</label>
      <div class="col-sm-10">
        <%= f.file_field :file %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Северна ширина</label>
      <div class="col-sm-10">
        <%= f.text_field :lat_one, autocomplete: "off", class: "form-control", placeholder: "Пример: 47.49882" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Източна дължина</label> 
      <div class="col-sm-10">
        <%= f.text_field :lat_two, autocomplete: "off", class: "form-control", placeholder: "Пример: 104.58539" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Сигнализиране", class: "btn btn-default" %> 
      </div>
    </div>
<% end %>
</div>

social_problems_rails_bg/app/views/problems/show.html.erb
	<div class="col-lg-3 col-md-6" style="width:100%;">
		<div class="panel panel-red">
			<div class="panel-heading" style="overflow: auto;">
				<span class="btn-group pull-left"> 
				  <div class="row">
				    <div class="col-xs-9 text-left">
				      <div><%= @problem.id %></div>
				    </div>
				  </div>
				  </span>
				  <span class="btn-group pull-right">Send</span>
			</div>
			<div class="panel-footer" style="color: black;">
			  <span class="pull-left"><%= @problem.description %></span>
				<% if @problem.picture %>
			 	 <span class="pull-right"><a href="\<%= @problem.picture.slice(7..-1) %>" ><img style="width:200px; height: 100px;	" src="\<%= @problem.picture.slice(7..-1) %>" /></a></span>	
				<% end %>
			  <div class="clearfix"></div>
			</div>
		</div>
	<% if @problem.lat_two and @problem.lat_one %>
		<div id="map">
			<script type="text/javascript" src="map/javascript.js"></script><div style="overflow:hidden;height:450px;width:100%;border: 8px solid #888; border-radius: 13px;"><div id="gmap_canvas" style="height:500px; width:100%;"></div><div style="#gmap_canvas img{max-width:none!important;background:none!important}"></div><a class="google-map-code" href="http://wordpress-themes.org" id="get-map-data">wordpress-themes.org</a></div><script type="text/javascript"> function init_map(){var myOptions = {zoom:15,center:new google.maps.LatLng(<%= @problem.lat_one %>, <%= @problem.lat_two %>),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(<%= @problem.lat_one %>, <%= @problem.lat_two %>)});infowindow = new google.maps.InfoWindow({content:"<b>AN DER BURG 25</b><br/>M&Uuml;HLHAUSEN, 99974<br/> M&uuml;hlhausen" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
		</div>
	<% end %>	
</div>